import { DrawingStroke, Point, User } from './types.js';
export declare class WebSocketManager {
    private socket;
    private roomId;
    private currentUserId;
    private pendingJoin;
    private onUserJoined?;
    private onUserLeft?;
    private onDrawingStart?;
    private onDrawingMove?;
    private onDrawingEnd?;
    private onCursorMove?;
    private onUndo?;
    private onRedo?;
    private onClear?;
    private onStateSync?;
    private onError?;
    private onConnected?;
    private onDisconnected?;
    connect(serverUrl?: string): void;
    setCallbacks(callbacks: {
        onUserJoined?: (user: User, users: User[]) => void;
        onUserLeft?: (userId: string, users: User[]) => void;
        onDrawingStart?: (stroke: DrawingStroke) => void;
        onDrawingMove?: (strokeId: string, point: Point) => void;
        onDrawingEnd?: (stroke: DrawingStroke) => void;
        onCursorMove?: (userId: string, point: Point) => void;
        onUndo?: (strokeId: string) => void;
        onRedo?: (stroke: DrawingStroke) => void;
        onClear?: (roomId: string) => void;
        onStateSync?: (strokes: DrawingStroke[], users: User[]) => void;
        onError?: (message: string) => void;
        onConnected?: () => void;
        onDisconnected?: () => void;
    }): void;
    joinRoom(roomId: string, userName?: string): boolean;
    leaveRoom(roomId: string): void;
    sendDrawingStart(point: Point, tool: string, color: string, lineWidth: number): void;
    sendDrawingMove(point: Point): void;
    sendDrawingEnd(strokeId: string): void;
    sendCursorMove(point: Point): void;
    sendUndo(): void;
    sendRedo(): void;
    sendClear(): void;
    requestState(): void;
    disconnect(): void;
    isConnected(): boolean;
    setUserId(userId: string): void;
    getRoomId(): string;
}
//# sourceMappingURL=websocket.d.ts.map